dataset-path-train: '/mnt/myhdd/anhnv/intrustion_ditection/ST-GCN-Pytorch/data/train_4classes_visual'  
dataset-path-test: '/mnt/myhdd/anhnv/intrustion_ditection/ST-GCN-Pytorch/data/test_4classes_visual'
epochs: 80
project: 'runs'
batch-size: 64
img-size: 64
num-frame: 30

